# Generated by Django 3.2.5 on 2021-08-16 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWelfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthWelfare_ID', models.CharField(max_length=3)),
                ('HealthWelfare_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LesionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_statusid', models.CharField(max_length=4)),
                ('lesion_statusname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('birthday', models.DateField()),
                ('HealthWelfare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadimg.healthwelfare')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('lesion_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lesiondetail', models.TextField(max_length=200)),
                ('lesion_statusid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadimg.lesionstatus')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesionPatient', to='uploadimg.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.TextField()),
                ('img_value', models.IntegerField(default=0)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagePatient', to='uploadimg.patient')),
            ],
            options={
                'db_table': 'myapp_image',
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('care_date', models.DateField(default=django.utils.timezone.now)),
                ('lesion_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nurse_id', models.CharField(max_length=8)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('size', models.IntegerField(default=0)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadimg.patient')),
            ],
        ),
    ]
