# Generated by Django 3.2.5 on 2021-08-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesion',
            name='id',
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
