# Generated by Django 3.2.5 on 2021-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_id', models.CharField(max_length=6)),
                ('Disease_name', models.CharField(max_length=255)),
            ],
        ),
    ]
