# Generated by Django 3.2.5 on 2021-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0002_auto_20210809_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
