# Generated by Django 3.2.5 on 2021-08-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0002_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Disease_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadimg.disease'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='Disease_id',
            field=models.CharField(max_length=5),
        ),
    ]
