# Generated by Django 3.2.5 on 2021-08-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0003_auto_20210816_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='lesion_statusid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadimg.lesionstatus'),
        ),
    ]
