# Generated by Django 3.2.5 on 2021-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0004_care_lesion_statusid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
