# Generated by Django 3.2.5 on 2021-08-12 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0004_alter_care_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='care',
            name='care_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
