# Generated by Django 3.2.5 on 2021-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0005_auto_20210812_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.AlterField(
            model_name='nurse',
            name='nurse_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
