# Generated by Django 3.2.5 on 2021-09-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0005_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
