# Generated by Django 3.2.5 on 2021-09-15 18:09

from django.db import migrations, models
import uploadimg.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0006_remove_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20, verbose_name=uploadimg.models.Patient.age),
            preserve_default=False,
        ),
    ]
