# Generated by Django 3.2.5 on 2021-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimg', '0008_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.CharField(max_length=3)),
                ('frame_name', models.CharField(max_length=3)),
                ('frame_size', models.CharField(max_length=10)),
                ('frame_pixel', models.CharField(max_length=10)),
            ],
        ),
    ]
